  - name: url-shortener
  # а тут то что писать, я откуда знаю какие модули нужны, чтоб запускать докер-композ
  # значит так: надо собрать .env из шаблона, собрать композ, и повесить хендлер на изменение шаблона чтоб он пересобирал композ