---
- name: Url-shortener installation
  hosts: url_shortener
  become: true
  roles:
    - { role: common, tags: [common] }
    - { role: docker, tags: [docker] }
    - { role: url_shortener, tags: [app] }
